
project_id = "diadwozorwkzhexhjfgb"

[api]
port = 54321
schemes = ["http", "https"]
host = "127.0.0.1"

[[extends]]
file = "supabase/config.base.toml"

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327

[auth]
port = 54328

[meta]
port = 54329

[vector]
port = 54330

[realtime]
port = 54331

[functions.customer-history]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.assign-default-role]
verify_jwt = false

[functions.auth-security]
verify_jwt = false

[functions.appointments]
verify_jwt = false

[functions.daily-metrics]
verify_jwt = false

[functions.database-analysis]
verify_jwt = false

[functions.make-voice-call]
verify_jwt = false

[functions.predictive-analytics]
verify_jwt = false

[functions.protected-example]
verify_jwt = false

[functions.public-example]
verify_jwt = false

[functions.queue-actions]
verify_jwt = false

[functions.queue-position]
verify_jwt = false

[functions.queue-stats]
verify_jwt = false

[functions.queue-status]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.send-communication]
verify_jwt = false

[functions.service-metrics]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.staff-metrics]
verify_jwt = false
